name: Card Availability Monitor
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      
      - name: Run monitor
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          PORTAL_USERNAME: ${{ secrets.PORTAL_USERNAME }}
          PORTAL_PASSWORD: ${{ secrets.PORTAL_PASSWORD }}
        run: python monitor.py > output.log 2>&1 || echo "Script failed"
      
      - name: Configure artifact upload
        run: echo "{ \"artifact_server_url\": \"$ACTIONS_RUNTIME_URL\" }" > $RUNNER_TEMP/.artifactrc
      
      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: debug-artifacts
          path: |
            output.log
            page.html
          retention-days: 1
